version: '3.7'

services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=todolist
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123456
            - TZ=Asia/Shanghai
        volumes:
            - ./config/sql:/docker-entrypoint-initdb.d/
        ports:
            - "3307:3306"