// Code generated by hertz generator.

package main

import (
	"Todolist/biz/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()
	h := server.Default()
	register(h)
	h.Spin()
}
