// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	model "Todolist/biz/router/model"
	task "Todolist/biz/router/task"
	user "Todolist/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	model.Register(r)
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	task.Register(r)

	user.Register(r)

}
